[versions]
# SDK Versions
minSdk = "26"
targetSdk = "36"
compileSdk = "36"

# Included build
# On 9.0.0 bump:
# - remove failOnNoDiscoveredTests
androidGradlePlugin = "9.0.0"
androidTools = "31.13.2"

# Plugins
dependency-analysis = "3.5.1"
detekt = "1.23.8"
jetbrains-compose = "1.10.0"
ksp = "2.3.4"
kotlin = "2.3.0"

# Libraries
browser = "1.9.0"
coil = "3.3.0"
compose-placeholder = "1.0.12"
compose-rules = "0.5.3"
datastore = "1.2.0"
desugar-jdk-libs = "2.1.5"
jetbrains-navigation = "2.9.1"
junit = "4.13.2"
junit-vintage = "6.0.2"
kmlogging = "2.1.0"
kotest = "6.0.7"
kotlin-inject = "0.9.0"
kotlin-inject-anvil = "0.1.6"
kotlin-inject-viewmodel = "0.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.9.0"
ktor = "3.3.3"
material3 = "1.10.0-alpha05"
material-icons-extended = "1.7.3"
materialKolor = "4.1.0"
mockk = "1.14.7"
okio = "3.16.4"
paging = "3.4.0-rc01"
robolectric = "4.16"
room = "2.8.4"
sandwich = "2.2.0"
sentry-android = "5.12.2"
sentry-kmp = "0.23.0"
signum = "3.19.1"
sqlite = "2.6.2"
turbine = "1.2.1"
work = "2.11.0"

[libraries]
# Included build
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
jetbrains-compose-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "jetbrains-compose" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# Features & components
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
compose-placeholder = { group = "com.eygraber", name = "compose-placeholder-material3", version.ref = "compose-placeholder" }
compose-rules = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "compose-rules"  }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
jetbrains-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
jetbrains-compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose" }
jetbrains-compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "jetbrains-compose" }
jetbrains-compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "jetbrains-compose" }
jetbrains-compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "jetbrains-compose" }
jetbrains-compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "jetbrains-compose" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "jetbrains-navigation" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit-vintage" }
kmlogging = { group = "com.diamondedge", name = "logging", version.ref = "kmlogging" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-extensions-htmlreporter = { group = "io.kotest", name = "kotest-extensions-htmlreporter", version.ref = "kotest" }
kotest-extensions-junitxml = { group = "io.kotest", name = "kotest-extensions-junitxml", version.ref = "kotest" }
kotlin-inject-anvil-compiler = { group = "software.amazon.lastmile.kotlin.inject.anvil", name = "compiler", version.ref = "kotlin-inject-anvil" }
kotlin-inject-anvil-runtime = { group = "software.amazon.lastmile.kotlin.inject.anvil", name = "runtime", version.ref = "kotlin-inject-anvil" }
kotlin-inject-anvil-runtime-optional = { group = "software.amazon.lastmile.kotlin.inject.anvil", name = "runtime-optional", version.ref = "kotlin-inject-anvil" }
kotlin-inject-compiler = { group = "me.tatarka.inject", name = "kotlin-inject-compiler-ksp", version.ref = "kotlin-inject" }
kotlin-inject-runtime = { group = "me.tatarka.inject", name = "kotlin-inject-runtime", version.ref = "kotlin-inject" }
kotlin-inject-viewmodel-compiler = { group = "com.teobaranga.kotlin.inject.viewmodel", name = "compiler", version.ref = "kotlin-inject-viewmodel" }
kotlin-inject-viewmodel-runtime = { group = "com.teobaranga.kotlin.inject.viewmodel", name = "runtime", version.ref = "kotlin-inject-viewmodel" }
kotlin-inject-viewmodel-runtime-compose = { group = "com.teobaranga.kotlin.inject.viewmodel", name = "runtime-compose", version.ref = "kotlin-inject-viewmodel" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ktor-client-auth = { group = "io.ktor", name ="ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name ="ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name ="ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name ="ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name ="ktor-serialization-kotlinx-json", version.ref = "ktor" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
sandwich = { group = "com.github.skydoves", name = "sandwich", version.ref = "sandwich" }
sandwich-ktor = { group = "com.github.skydoves", name = "sandwich-ktor", version.ref = "sandwich" }
signum-indispensable = { module = "at.asitplus.signum:indispensable", version.ref = "signum" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite"}
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
work = { group = "androidx.work", name = "work-runtime", version.ref = "work"  }

[plugins]
# Plugins defined by this project
monica-android-application = { id = "monica.android.application", version = "unspecified" }
monica-android-library = { id = "monica.android.library", version = "unspecified" }
monica-cmp = { id = "monica.cmp", version = "unspecified" }
monica-kotlin-inject = { id = "monica.kotlin.inject", version = "unspecified" }
monica-kmp = { id = "monica.kmp", version = "unspecified" }
monica-network = { id = "monica.network", version = "unspecified" }

androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
sentry-android = { id = "io.sentry.android.gradle", version.ref = "sentry-android" }
sentry-kmp = { id = "io.sentry.kotlin.multiplatform.gradle", version.ref = "sentry-kmp" }
