[versions]
# SDK Versions
minSdk = "24"
targetSdk = "35"
compileSdk = "36"

# Included build
androidGradlePlugin = "8.11.1"
androidTools = "31.11.1"

# Plugins
crashlytics = "3.0.5"
dependency-analysis = "2.19.0"
detekt = "1.23.8"
google-services = "4.4.3"
jetbrains-compose = "1.9.0-beta01"
jetbrains-lifecycle = "2.9.1"
ksp = "2.2.0-2.0.2"
kotlin = "2.2.0"

# Libraries
browser = "1.8.0"
coil = "3.3.0"
compose-placeholder = "1.0.11"
compose-rules = "0.4.26"
datastore = "1.1.7"
desugar-jdk-libs = "2.1.5"
firebase-bom = "34.0.0"
jetbrains-navigation = "2.9.0-beta04"
junit = "4.13.2"
junit-vintage = "5.13.4"
kmlogging = "2.0.3"
kotest = "6.0.0.M5"
kotlin-inject = "0.8.0"
kotlin-inject-anvil = "0.1.6"
kotlin-inject-viewmodel = "0.3.0"
kotlinx-coroutines = "1.10.2"
# KMLogging is problematic after the last update because it depends on kotlinx.datetime.Clock
# https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#deprecation-of-instant
kotlinx-datetime = "0.7.1-0.6.x-compat"
kotlinx-serialization = "1.9.0"
ktor = "3.2.2"
material3 = "1.9.0-alpha04"
materialKolor = "3.0.1"
mockk = "1.14.5"
paging = "3.3.6"
robolectric = "4.15.1"
room = "2.7.2"
sandwich = "2.1.2"
turbine = "1.2.1"
work = "2.10.2"

[libraries]
# Included build
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
jetbrains-compose-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "jetbrains-compose" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# Features & components
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
compose-placeholder = { group = "com.eygraber", name = "compose-placeholder-material3", version.ref = "compose-placeholder" }
compose-rules = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "compose-rules"  }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "jetbrains-compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
jetbrains-compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version = "1.8.2" }
jetbrains-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }
jetbrains-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "jetbrains-navigation" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit-vintage" }
kmlogging = { group = "com.diamondedge", name = "logging", version.ref = "kmlogging" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-extensions-htmlreporter = { group = "io.kotest", name = "kotest-extensions-htmlreporter", version.ref = "kotest" }
kotest-extensions-junitxml = { group = "io.kotest", name = "kotest-extensions-junitxml", version.ref = "kotest" }
kotlin-inject-anvil-compiler = { group = "software.amazon.lastmile.kotlin.inject.anvil", name = "compiler", version.ref = "kotlin-inject-anvil" }
kotlin-inject-anvil-runtime = { group = "software.amazon.lastmile.kotlin.inject.anvil", name = "runtime", version.ref = "kotlin-inject-anvil" }
kotlin-inject-anvil-runtime-optional = { group = "software.amazon.lastmile.kotlin.inject.anvil", name = "runtime-optional", version.ref = "kotlin-inject-anvil" }
kotlin-inject-compiler = { group = "me.tatarka.inject", name = "kotlin-inject-compiler-ksp", version.ref = "kotlin-inject" }
kotlin-inject-runtime = { group = "me.tatarka.inject", name = "kotlin-inject-runtime", version.ref = "kotlin-inject" }
kotlin-inject-viewmodel-compiler = { group = "com.teobaranga.kotlin.inject.viewmodel", name = "compiler", version.ref = "kotlin-inject-viewmodel" }
kotlin-inject-viewmodel-runtime = { group = "com.teobaranga.kotlin.inject.viewmodel", name = "runtime", version.ref = "kotlin-inject-viewmodel" }
kotlin-inject-viewmodel-runtime-compose = { group = "com.teobaranga.kotlin.inject.viewmodel", name = "runtime-compose", version.ref = "kotlin-inject-viewmodel" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ktor-client-auth = { group = "io.ktor", name ="ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name ="ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name ="ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name ="ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name ="ktor-serialization-kotlinx-json", version.ref = "ktor" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
sandwich = { group = "com.github.skydoves", name = "sandwich", version.ref = "sandwich" }
sandwich-ktor = { group = "com.github.skydoves", name = "sandwich-ktor", version.ref = "sandwich" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
work = { group = "androidx.work", name = "work-runtime", version.ref = "work"  }

[plugins]
# Plugins defined by this project
monica-android-application = { id = "monica.android.application", version = "unspecified" }
monica-android-library = { id = "monica.android.library", version = "unspecified" }
monica-cmp = { id = "monica.cmp", version = "unspecified" }
monica-kotlin-inject = { id = "monica.kotlin.inject", version = "unspecified" }
monica-kmp = { id = "monica.kmp", version = "unspecified" }
monica-network = { id = "monica.network", version = "unspecified" }

androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
